spring:
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: codigo
      host: 0.0.0.0
      port: 27017
      database: localmongo

app-config:
  cache:
    host: 0.0.0.0
    port: 6379
    ttl: 600
    scheduler: 0 * * * * *
    redis-enabled: true
