version: '3'
services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: codigo
    ports:
      - "27017:27017"
    volumes:
      - home/volumes/data/db

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass TeSteAdR
    volumes:
      - cache:/data
volumes:
  cache:
    driver: local